"""empty message

Revision ID: 381b6a4ffe3b
Revises: 2786bd412828
Create Date: 2025-02-01 12:39:41.674168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381b6a4ffe3b'
down_revision: Union[str, None] = '2786bd412828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pregnancy_calendar', sa.Column('date_start', sa.Date(), nullable=False))
    op.add_column('pregnancy_calendar', sa.Column('date_end', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pregnancy_calendar', 'date_end')
    op.drop_column('pregnancy_calendar', 'date_start')
    # ### end Alembic commands ###
