"""empty message

Revision ID: 4492a7ea8042
Revises: 7a296e487b7d
Create Date: 2025-05-16 11:41:52.018325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4492a7ea8042'
down_revision: Union[str, None] = '7a296e487b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('description_lite', sa.Text(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'description_lite')
    # ### end Alembic commands ###
