"""empty message

Revision ID: 67a34fdec1bb
Revises: 4492a7ea8042
Create Date: 2025-05-16 11:45:34.430669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a34fdec1bb'
down_revision: Union[str, None] = '4492a7ea8042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('description_lite', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'description_lite')
    # ### end Alembic commands ###
