"""empty message

Revision ID: 7a296e487b7d
Revises: 381b6a4ffe3b
Create Date: 2025-02-01 20:11:12.886640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a296e487b7d'
down_revision: Union[str, None] = '381b6a4ffe3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pregnancy_calendar', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pregnancy_calendar', 'name')
    # ### end Alembic commands ###
