"""empty message

Revision ID: 8bf6e0577112
Revises: bf754d6c323a
Create Date: 2025-01-28 17:04:28.240540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf6e0577112'
down_revision: Union[str, None] = 'bf754d6c323a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('date_publications', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'date_publications')
    # ### end Alembic commands ###
