"""empty message

Revision ID: bf754d6c323a
Revises: d8f4b27e7073
Create Date: 2025-01-27 22:56:00.312035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf754d6c323a'
down_revision: Union[str, None] = 'd8f4b27e7073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('content', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'content')
    # ### end Alembic commands ###
