"""empty message

Revision ID: d20a2b17f525
Revises: 67a34fdec1bb
Create Date: 2025-05-27 10:19:29.675408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20a2b17f525'
down_revision: Union[str, None] = '67a34fdec1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mood_emoji', sa.String(), server_default='😊', nullable=True))
    op.add_column('user', sa.Column('birth_date', sa.Date(), server_default='2025-05-27 10:19:28.800353', nullable=True))
    op.add_column('user', sa.Column('city', sa.String(), server_default='Неизвестно', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'city')
    op.drop_column('user', 'birth_date')
    op.drop_column('user', 'mood_emoji')
    # ### end Alembic commands ###
